WARMUP=3 SCENARIO=Server PRO_INTER=4 PRO_INTRA=4 PRO_BS=32 INTER=0 INTRA=8 BS=64 LEN=4 RESPONSE=1 ./launch_sut.sh

#WARMUP=3 SCENARIO=Offline INTER=1 INTRA=4 BS=32 ./launch_sut.sh
#WARMUP=3 SCENARIO=Server PRO_INTER=2 PRO_INTRA=4 PRO_BS=32 INTER=28 INTRA=8 BS=64 LEN=4 RESPONSE=1 ./launch_sut.sh
